# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local olaoyefaith/udagram-frontend:v1
    - run: docker tag udagram-api-feed olaoyefaith/udagram-api-feed:v1
    - run: docker tag udagram-api-user olaoyefaith/udagram-api-user:v1
    - run: docker tag udagram-reverseproxy olaoyefaith/udagram-reverseproxy:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-std
    - run: docker push olaoyefaith/udagram-frontend:v1
    - run: docker push olaoyefaith/udagram-api-feed:v1
    - run: docker push olaoyefaith/udagram-api-user:v1
    - run: docker push olaoyefaith/udagram-reverseproxy:v1
